//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temperature
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> temperature { get; set; }
        public Nullable<int> City_id { get; set; }
    
        public virtual City City { get; set; }
    }
}
